---
- hosts: master
  remote_user: 'ubuntu'
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
# Basic Installation
    - name: Install Basics
      include: tasks/basic.yml
      when: "{{ master_basics }}"
# Update hosts
    - name: Update host information
      include: tasks/update_host.yml
# Copy files
    - name: Copy Files
      include: tasks/copy.yml
# Start Kubernetes
    - name: Start Kubelet
      service: name=kubelet state=started
      when: "{{ kube_init }}"
    - name: Run kubeadm init
      command: /usr/bin/kubeadm init --token "{{ token }}"
      when: "{{ kube_init }}"
# Stop Kubernetes
    - name: Stop Kubernetes 
      include: tasks/stop_kube.yml
      when: "{{ kube_stop }}"
# Ansible from Master
    - name: Run Ansible from master
      command: chdir=/home/ubuntu/mykube  /usr/bin/ansible-playbook -i inventory.conf  --key-file="{{ key }}" slave.yml
    - name: Run pod network
      command: /usr/bin/kubectl apply -f https://git.io/weave-kube
      when: "{{ kube_basics }}"
    - name: Clone dashboard repo
      git: repo=https://github.com/kubernetes/dashboard.git dest=/home/ubuntu/dashboard clone=yes update=no
      when: "{{ kube_basics }}"
    - name: Start dashboard
      command: /usr/bin/kubectl create -f /home/ubuntu/dashboard/src/deploy/kubernetes-dashboard.yaml
      when: "{{ kube_basics }}"
