---
- hosts: master
  remote_user: 'ubuntu'
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
    - name: apt-get update 
      raw: apt-get update
    - name: Install python 2.7
      raw:  apt install -y python-minimal
    - name: Adding ansible repo
      raw: apt-add-repository -y ppa:ansible/ansible
    - name: curls
      raw: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    - name: adding sources
      lineinfile: create=yes dest=/etc/apt/sources.list.d/kubernetes.list line="deb http://apt.kubernetes.io/ kubernetes-xenial main" 
    - name: apt-get update 
      raw: apt-get update
    - name: Install kubadm and related packages
      apt: pkg={{ item }} state=installed
      with_items:
         - ansible
         - docker.io
         - kubelet 
         - kubeadm 
         - kubectl 
         - kubernetes-cni
    - name: Update host
      lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line="127.0.0.1 localhost {{ local_host }}"
    - name: Update host with nodes
      lineinfile: dest=/etc/hosts line="{{ item.ip }} {{ item.name }}"
      with_items: "{{ nodes }}"
    - name: Copy inventory
      copy: src=inventory.conf dest=/home/ubuntu/mykube/
    - name: Copy keypair
      copy: src={{ key }} dest=/home/ubuntu/mykube/ mode=600
    - name: Copy slave.yml
      copy: src=slave.yml dest=/home/ubuntu/mykube/
    - name: Add host to user
      raw: ssh-keyscan -H "{{ item.name }}"  | tee --append /root/.ssh/known_hosts
      with_items: "{{ nodes }}"
    - name: Start Kubelet
      service: name=kubelet state=started
    - name: Run kubeadm init
      command: /usr/bin/kubeadm init --token "{{ token }}"
    - name: Run Ansible from master
      command: chdir=/home/ubuntu/mykube  /usr/bin/ansible-playbook -i inventory.conf  --key-file="{{ key }}" slave.yml

      
