---
- hosts: slaves
  remote_user: 'ubuntu'
  become: yes
  become_method: sudo
  gather_facts: False
  tasks:
# Basic Installation
    - name: Install Basics
      include: tasks/basic.yml
      when: "{{ node_basics }}"
# Start Kubernetes
    - name: Start Kubelet
      service: name=kubelet state=started
      when: "{{ kube_join }}"
    - name: Run kubeadm join
      command: /usr/bin/kubeadm join --skip-preflight-checks --token "{{ token }}" "{{ master_ip }}" 
      when: "{{ kube_join }}"
# Stop Kubernetes
    - name: Stop Kubernetes 
      include: tasks/stop_kube.yml
      when: "{{ kube_stop }}"
