---
- name: Copy inventory
  copy: src=inventory.conf dest=/home/ubuntu/mykube/
- name: Copy keypair
  copy: src={{ key }} dest=/home/ubuntu/mykube/ mode=600
- name: Copy slave.yml
  copy: src=slave.yml dest=/home/ubuntu/mykube/
- name: Copy ansible.cfg
  copy: src=ansible.cfg dest=/home/ubuntu/mykube/
- name: Copy tasks
  copy: src=tasks/ dest=/home/ubuntu/mykube/tasks/
- name: Copy k8s files
  copy: src=k8s/ dest=/home/ubuntu/mykube/k8s/
