---
- name: Run pod network
  command: /usr/bin/kubectl apply -f https://git.io/weave-kube
- name: Clone heapster repo
  git: repo=https://github.com/kubernetes/heapster.git dest=/home/ubuntu/heapster clone=yes update=no
- name: Start heapster
  command: /usr/bin/kubectl apply -f /home/ubuntu/heapster/deploy/kube-config/influxdb
- name: Wait for Heapster
  wait_for: host=0.0.0.0 delay=30
- name: Clone dashboard repo
  git: repo=https://github.com/kubernetes/dashboard.git dest=/home/ubuntu/dashboard clone=yes update=no
- name: Start dashboard
  command: /usr/bin/kubectl create -f /home/ubuntu/dashboard/src/deploy/kubernetes-dashboard.yaml
