---
- name: Run pod network
  command: /usr/bin/kubectl apply -f https://git.io/weave-kube
- name: Clone heapster repo
  git: repo=https://github.com/kubernetes/heapster.git dest=/home/ubuntu/heapster clone=yes update=no
- name: Start heapster
  command: /usr/bin/kubectl apply -f /home/ubuntu/heapster/deploy/kube-config/influxdb
- name: Wait for Heapster
  wait_for: host=127.0.0.1 delay=30
#- name: Clone dashboard repo
#  git: repo=https://github.com/kubernetes/dashboard.git dest=/home/ubuntu/dashboard clone=yes update=no
- name: Start dashboard
  command: /usr/bin/kubectl create -f /home/ubuntu/mykube/k8s/kubernetes-dashboard.yaml
- name: Wair for dashboard
  wait_for: host=127.0.0.1 delay=30
- name: Start WeaveScope
  command: /usr/bin/kubectl apply -f /home/ubuntu/mykube/k8s/weavescope.yaml

