---
- name: Stop Kubelet 
  service: name=kubelet state=stopped 
- name: Delete docker containers
  raw:  /usr/bin/docker rm -f -v $(/usr/bin/docker ps -a -q)
- name: Unmount
  raw: find /var/lib/kubelet | xargs -n 1 findmnt -n -t tmpfs -o TARGET -T | uniq | xargs -r umount -v
- name: Delete kubenertes configuration files
  raw: rm -r -f /etc/kubernetes /var/lib/kubelet /var/lib/etcd
