---
- name: Update /etc/hosts
  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line="127.0.0.1 localhost {{ local_host }}"
- name: Update /etc/hosts with nodes
  lineinfile: dest=/etc/hosts line="{{ item.ip }} {{ item.name }}"
  with_items: "{{ nodes }}"
- name: Remove nknown_hosts
  file: path=/root/.ssh/known_hosts state=absent
- name: Add nodes to known_hosts for ssh
  raw: ssh-keyscan -H "{{ item.name }}"  | tee --append /root/.ssh/known_hosts
  with_items: "{{ nodes }}"
