kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: sqre
  name: pod-master
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods"]
  verbs: ["*"] # You can also use ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-master-binding
  namespace: sqre
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-master
subjects:
  - kind: ServiceAccount
    name: default
    namespace: sqre
